### PR TITLE
PVA over TLS

### PR DESCRIPTION
**Pull request by mdavidsaver**
Preliminary work on applying OpenSSL to PVXS.

Client search requests include two "protocol" names: `tcp` and `tls`.  Server listens on a second TCP port for TLS connections, prefers to respond with `tls` when both present.

Adds `x509` AUTHZ method.  Client advertises `x509` when configured with a client cert.  Server prefers `x509` to `ca`.  If selected, uses client cert `commonName` as account name.  eg. `CN=foo` appears to ACF logic as `foo`.  (note, this really needs an extension to the ACF logic to account for different source of accounts)

TLS features/restrictions

- OpenSSL >= 3.0
- TLS protocol version >= 1.3 required
- ALPN extension negotiates with protocol `pva/1`.  (mandatory?)
- Client/server reload TLS configuration (eg. replace cert) at runtime.  Forces closes connections.

New Configuration:

- `$EPICS_PVAS_TLS_KEYCHAIN` `$EPICS_PVA_TLS_KEYCHAIN` name of a PKCS12 file containing some combination of key, server/client certificate, and/or CA certificates.  The file path may optionally be followed by `;` and a password.  eg. `EPICS_PVAS_TLS_KEYCHAIN=/path/to/some.p12;secret`.
- `$EPICS_PVAS_TLS_PORT` `$EPICS_PVA_TLS_PORT` default port to listen for TLS connections
- `$OPENSSL_CONF` Location of OpenSSL [config file](https://www.openssl.org/docs/man3.1/man5/config.html).  Defaults to `/usr/lib/ssl/openssl.cnf` on Linux.  Application name `pvxs` is used.
- `$SSLKEYLOGFILE` If set, TLS session keys will be written here. eg. for use by [wireshark](https://wiki.wireshark.org/TLS).  cf. https://github.com/mdavidsaver/cashark/pull/14

Building:

`libevent` must be built with optional openssl support (bundled build will detect).  `openssl` is expected to be installed in the default search path.  I have no plans to bundled openssl.

Currently, python3-pyopenssl is also required.  This is planned to be temporary during development.

TODO:

- [X] Configure TLS in `$EPICS_PVA_NAME_SERVERS` w/ URI-ish `pvas://1.2.3.4:5678`.
- [X] Verify interoperability with PKCS12 created by java `keytool`  (OpenSSL parser for PKCS12 is... limited)
  - [X] Can work with files created by `openssl pkcs12` or `keytool`.  (although Java can't current work with openssl created files)
  - [X] Handle password protected PKCS12 (which java keytool insists on...)
- [X] Fix OSX RPATH issue
- [X] IOC shell commands to manage TLS (re)configuration
- [X] Test server reconfigure
  - [X] Expose server credentials to client
- [X] `x509` AUTHZ method design
  - [X] Add `authority` alongside `method` and `account`
- [ ] What to do about CMD_BEACON ?
- [ ] OSCP...
- [ ] What to do about certificate expiration?  (drop credentials?  force reconnect w/o TLS?)
- [ ] Include CA IDs in search request/reply?  (more graceful fallback if mis-matched CA certs)
- [ ] Update python module build
- [ ] Investigate openssl provider/engine support.  eg [tpm2-openssl](https://github.com/tpm2-software/tpm2-openssl)

@george-mcintyre @kasemir @gregoryraymondwhite fyi.  Something to discuss.  May be ready for early testing.  Definitely not ready for wider testing (no documentation, config. inputs may change).

### CODE REVIEW

**Comment by gregoryraymondwhite** [comment]
Thanks very much Michael. Excellent. Can you work with Ernest on early testing ? BTW I’m away until Aug 10.

Greg

On Jul 26, 2023, at 4:01 AM, mdavidsaver ***@***.***> wrote:

﻿

Preliminary work on applying OpenSSL to PVXS.

Client search requests include two "protocol" names: tcp and tls. Server listens on a second TCP port for TLS connections, prefers to respond with tls when both present.

Adds x509 AUTHZ method. Client advertises x509 when configured with a client cert. Server prefers x509 to ca. If selected, uses client cert commonName as account name. eg. CN=foo appears to ACF logic as x509/foo.

TLS features/restrictions

  *   OpenSSL >= 3.0
  *   TLS protocol version >= 1.3 required
  *   ALPN extension negotiates with protocol pva/1. (mandatory?)
  *   Client/server reload TLS configuration (eg. replace cert) at runtime. Forces closes connections.

New Configuration:

  *   $EPICS_PVAS_TLS_KEYCHAIN $EPICS_PVA_TLS_KEYCHAIN name of a PKCS12 file containing some combination of key, server/client certificate, and/or CA certificates.
  *   $EPICS_PVAS_CA_DIRS $EPICS_PVA_CA_DIRS $EPICS_PVAS_CA_FILES $EPICS_PVA_CA_FILES space separated lists of either PEM encoded certificates, or OpenSSL style certificate directories.
  *   $EPICS_PVAS_TLS_PORT $EPICS_PVA_TLS_PORT default port to listen for TLS connections
  *   $OPENSSL_CONF Location of OpenSSL config file<https://www.openssl.org/docs/man3.1/man5/config.html>. Defaults to /usr/lib/ssl/openssl.cnf on Linux. Application name pvxs is used.
  *   $SSLKEYLOGFILE If set, TLS session keys will be written here. eg. for use by wireshark<https://wiki.wireshark.org/TLS>.

Building:

libevent must be built with optional openssl support (bundled build will detect). openssl is expected to be installed in the default search path. I have no plans to bundled openssl.

TODO:

  *    How to configure TLS in $EPICS_PVA_NAME_SERVERS?
  *    Verify interoperability with PKCS12 created by java keytool (OpenSSL parser for PKCS12 is... limited)
     *    cert/key
     *    cert/key/root CA
     *    cert/key/intermediate CA/root CA
     *    Only root
  *    Fix OSX RPATH issue
  *    IOC shell commands to manage TLS (re)configuration
  *    Test server reconfigure
     *    How to expose server credentials to client?
  *    x509 AUTHZ method design?
  *    OSCP (use CA commonName as prefix?)
  *    What to do about certificate expiration? (drop credentials? force reconnect w/o TLS?)
  *    Include CA IDs in search request/reply? (more graceful fallback if mis-matched CA certs)

@george-mcintyre<https://github.com/george-mcintyre> @kasemir<https://github.com/kasemir> @gregoryraymondwhite<https://github.com/gregoryraymondwhite> fyi. Something to discuss. May be ready for early testing. Definitely not ready for wider testing (no documentation, config. inputs may change).

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/mdavidsaver/pvxs-dev/pull/2

Commit Summary

  *   220df87<https://github.com/mdavidsaver/pvxs-dev/pull/2/commits/220df8749baa1ea6c42b3de5917aed925c098daf> update bundled libevent
  *   560a356<https://github.com/mdavidsaver/pvxs-dev/pull/2/commits/560a356a09780cf1475305a3318e61e83b95607b> conditionally link with libssl
  *   28cc210<https://github.com/mdavidsaver/pvxs-dev/pull/2/commits/28cc210813cbb567f47a7a97cb8bb5dae7b4ff15> WIP: libevent testing
  *   0cc14d9<https://github.com/mdavidsaver/pvxs-dev/pull/2/commits/0cc14d9f2894d84c13015745bb23457e1e426549> Add TLS support w/ OpenSSL

File Changes

(44 files<https://github.com/mdavidsaver/pvxs-dev/pull/2/files>)

  *   M .github/workflows/ci-scripts-build.yml<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-f734265827ede1e179c7638080c2ea333d346a46206938d495dfb12db36a6afa> (5)
  *   M .gitmodules<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584> (2)
  *   M Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52> (5)
  *   M bundle/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-4a84513b935ab620216d1a4dd4d3cdfadc5cc26184227ed816b83a8b439c7922> (3)
  *   M bundle/libevent<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-22082398fe78938deec241afd342a8099bf29695d187b4aebc4c8ae2b4d404a9> (2)
  *   M configure/CONFIG<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-ad4f052373686d699d10f9db5a0b7c2932a62db3c7e501b127cfc03e503cc76f> (1)
  *   D configure/CONFIG_PVXS_MODULE<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-b031d5f33670878d78f7a18bfd8b5f29775e882102839041a0a1524bff6474b2> (41)
  *   M configure/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-67681747ffb8a6dd8c17021a73626f104d3ee56e8987115d72f64f5b46b94912> (27)
  *   A configure/probe-openssl.c<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-355bff4c6b5ea65d29334df94961b02916dfae0a128b5a28c04e671d6e6b1fb5> (17)
  *   M configure/toolchain.c<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-b1c4aaf276891f8e6e89d1bedb65c4dabc235e3848554a213cf9fced666211d6> (3)
  *   M example/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-a7f0749bdafe7d4247c8435bbb139a3ca42c20bf58a96868ac286419afb764d1> (5)
  *   M ioc/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-4ed434d8e50c74edf9a7aefb5a0c5deb3a8737d125438d15951f5d3c6c5c7cea> (5)
  *   M qsrv/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-16d98241d4e2e4aeb9b1dbb18514ba2a42a0b09f9054635f6f7364f3c9ea44f1> (5)
  *   M setup.py<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7> (1)
  *   A setup/CONFIG_PVXS_MODULE<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-5720e9949ab642b8364344015283784f639d24c961b9c2163e86f763024cbcac> (34)
  *   A setup/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-162ab95123f7089b846c7985879a8cdc697b6cd20873ddc38a69877bd46a98b7> (50)
  *   R setup/RULES_PVXS_MODULE<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-eef2dc3add3f63363bef004b0cece530d24143266249e520284f54719c862d79> (2)
  *   A setup/TOOLCHAIN_PVXS.target@<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-9f87bd14a2dc95b9d39f4955021fa8482e0d3e909411667281ce8b819853a165> (3)
  *   M src/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-3e2513390df543315686d7c85bd901ca9256268970032298815d2f893a9f0685> (21)
  *   M src/client.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-7bc46552432fa03e009f9f455e4729312853d92775935ef20849797f24ac0c60> (79)
  *   M src/clientconn.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-64b68e6573e2a9e78beb9204e21119f77b52232d5cf241befe0221d69096728f> (64)
  *   M src/clientimpl.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-96ad5c86b996400a6d212ab2c855880d96ddb200ad8de4658e984e5a58be97f8> (13)
  *   M src/config.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-6b2f0a449fdefd8930e23ef0dcd752beec69242e1303d77653f047c5e0766385> (159)
  *   M src/conn.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-ffb923ace074d8b8d218c49ab6d2297cd66637b28a8f80e5fa4f6b0aad2c77b7> (14)
  *   M src/conn.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-7a0378987717d144eba20574d93aeca7833a9a071bb7feb56e7a060acf33c04f> (4)
  *   M src/describe.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-0d3366679a28cb4f68e1f4e63d820bc9da58b48fa3a7528b2f8f40e0d0553f72> (5)
  *   M src/evhelper.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-a2af6a2fc2f5034fb3762aea747b0ee50107aa306978f0099e44d4a0488b5169> (24)
  *   A src/ossl.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-3311ab554680a94721e6ec3016885b43c922c7c11d18c6dd3845ee3770405726> (400)
  *   A src/ossl.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-b95c2ccba3db3c9c0932a572ae90784bcb1dc2b75e7c2fd452255f7c89f88a33> (92)
  *   M src/pvxs/client.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-00ebea0a228c498f555f46b63b451e4270aa95a4e60496ea01921b26b82e7d4b> (12)
  *   M src/pvxs/netcommon.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-069e005205bb3d3a01afb0d241ffe2cd2e98e37b07f0b82a2b734902aee7d73d> (12)
  *   M src/pvxs/server.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-884cfb3af1e3c29cf60d0f0b97940dabf90c7c9435b1af1402e039fda8132e07> (15)
  *   M src/server.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-d0ecb51621381529aa2b31bb04fecee4a1b1b7dc0be53978c4878f2c4d4bfe1f> (84)
  *   M src/serverchan.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-b7c300c1f6386789096aafae630d454e0722d242a20082a03c62f19d2a3d5f00> (15)
  *   M src/serverconn.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-e3b187969c7a6a7df0e22b615372d9473da664f496db30c5705c0c52bedf8d3a> (75)
  *   M src/serverconn.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-2ab028e8276c74d555d6e82446232355e9a73535a402f5a444d3e814988eae38> (9)
  *   M src/udp_collector.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-3b4da8b2f8b04f3156e769cdfab0458418715afc240aac4c9c1fab553306a0c6> (4)
  *   M src/udp_collector.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-552dddf98fabcdb41c274fa4ed7e2e7aca43380860026113a608dbc2d98d74a9> (1)
  *   M src/utilpvt.h<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-aedaf5f636ed01af3c4ed7d58d3f3beae9d93c06f18f20808cbab6c9791e5fdc> (10)
  *   M test/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-740cb5a1689091cb894445e46683c255e39689ccba1c6c63d8a8841c8df8817d> (25)
  *   A test/gen_test_certs.py<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-f1de8464ceac7eddbf51126b3e0954bab8e9dc748c9a68d0bd78c3724b5c6e46> (213)
  *   A test/testtls.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-5302345634fcc298e9f42f0127b28bab98722cd07d48be02034342bf23f6bbd2> (188)
  *   M tools/Makefile<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-e327741dae7d1efd73c66ab134d50ac2c56187d814c443bb55464272b8b44113> (5)
  *   M tools/mshim.cpp<https://github.com/mdavidsaver/pvxs-dev/pull/2/files#diff-3deb8e40ddbc898ac4e6ea989d44d1a2662cd7acd1079b2fab95123312b14956> (4)

Patch Links:

  *   https://github.com/mdavidsaver/pvxs-dev/pull/2.patch
  *   https://github.com/mdavidsaver/pvxs-dev/pull/2.diff

**Comment by mdavidsaver** [comment]
Testing recipes:

Run `make runtests` an look in `test/O.Common` or explicitly run `test/gen_test_certs.py`.

```
EPICS_PVA_TLS_KEYCHAIN=test/O.common/ioc1.p12 ./bin/linux-x86_64/softIocPVA ...
```

and then one of:

```
EPICS_PVA_TLS_KEYCHAIN=test/O.common/client1.p12 pvxget ...
```

```
EPICS_PVA_CA_FILES=test/O.common/ca.pem pvxget ...
```

**Comment by mdavidsaver** [comment]
An item on the TODO list `Verify interoperability with PKCS12 ...`.  To facilitate interoperability testing, I am hoping to find a recipe to create a set of .p12 files generated with Java `keytool`, which are analogous to those created by `test/gen_test_certs.py`.

From what I can tell, Java and OpenSSL have somewhat [different interpretations](https://security.stackexchange.com/questions/230650/java-keystore-vs-openssl-implementations-of-pkcs12-files-they-seem-to-differ-d) of the PKCS#12 spec.

One difference between the two being that Java `keytool` will add an extra attribute to mark trusted root CA(s).  OpenSSL does not know about this attribute.

Another (potential) difference is in how the end point certificate is distinguished from intermediate/root CAs.  This may cause complications with a .p12 files containing only a root CA.  A keychain file with only a root CA seems a desirably as a common client configuration.

Also, I am not sure what to do about the possibility of multiple root CAs...

**Comment by mdavidsaver** [comment]
Updated with changes to:

- Add API calls, and ioc shell command `pvxreconfigure`.  Which re-reads (only) the TLS related environment variables, then force disconnects any clients.
- Reading of PKCS#12 files no longer makes assumptions about order.  I have tried to be flexible, inspecting certificate attributes, when deciding whether to place in trusted or untrusted lists.
- Add `ServerCredentials` to allow clients to inspect server "credentials", which are derived from the server cert. in the same manner as a server will do for a client certificate.  Accessed through client `Connected` exception, which may now also be passed to ConnectBuilder callbacks.

**Comment by kasemir** [comment]
As for interoperability of the PKCS12 files, the `ioc1.p12` works for the Java demo server.
`ca.pem` can be used for the Java client, except it needs to be turned into a PKCS12 file as done with `myca.cer` in step 3 below.

Here's an example of creating a similar 'ioc' and 'ca' using keytool. 

1) Create our own CA, and make its public certificate available as `myca.cer`:

```
keytool -genkeypair -alias myca -keystore ca.p12 -storepass changeit -dname "CN=myca" -keyalg RSA -ext bc=ca:true
keytool -list                   -keystore ca.p12 -storepass changeit
keytool -exportcert -alias myca -keystore ca.p12 -storepass changeit -rfc -file myca.cer
keytool -printcert -file myca.cer 
```

2) Now create a server keypair for use by the IOC:

```
keytool -genkeypair -alias myioc -keystore ioc.p12 -storepass changeit -dname "CN=myioc" -keyalg RSA
keytool -list -v                 -keystore ioc.p12 -storepass changeit
```

It starts out as a "self-signed certificate" with matching owner and issuer.
Create a certificate signing request. The CSR could be sent to a commercial CA, but we sign it with our own CA.

```
keytool -certreq -alias myioc -keystore ioc.p12 -storepass changeit -file myioc.csr
keytool -gencert -alias myca  -keystore ca.p12  -storepass changeit -ext san=dns:myioc -infile myioc.csr -outfile myioc.cer
keytool -printcert -file myioc.cer
```

Import the signed certificate into the ioc keystore. Since `ioc.cer` is signed by 'myca', which
is not a generally known CA, we will get an error like "Failed to establish chain"
unless we first import `myca.cer` to trust out local CA.

```
keytool -importcert -alias myca  -keystore ioc.p12 -storepass changeit -file myca.cer  -noprompt
keytool -importcert -alias myioc -keystore ioc.p12 -storepass changeit -file myioc.cer
keytool -list -v                 -keystore ioc.p12 -storepass changeit
```

3) For clients, create a truststore that holds just the CA certificate

A client will trust any IOC certificate signed by 'myca' once it's aware of the 'myca' certificate,
which needs to be imported into the PKCS12 file format:
```
keytool -importcert -alias myca  -keystore trust_ca.p12 -storepass changeit -file myca.cer  -noprompt
```


So now an IOC can use `ioc.p12`, and clients can use `trust_ca.p12`.
One could create additional `ioc*.p12`, in the extreme one per IOC, and clients would accept them all because they use the trusted CA.

**Comment by kasemir** [comment]
The tcp vs tls behavior is a little sticky on the server side.

1) Start softIocPVA with a ..PVAS_KEYCHAIN=ioc1.p12

2) Read via plain 'pvxget' and server sends a "tcp" search reply. That's good for older clients that don't support tls

3) Read via 'pvxget' that uses a suitable ..PVA_KEYCHAIN, so it searches for both tcp and tls, and server sends a "tls" search reply. That's good, new setups will prefer tls.

4) Try the plain pvxget again, it will search for "tcp" as before, but server still sends a "tls" reply.

..So once the server replied with "tls", it keeps doing that, no matter what the seach supports...

**Comment by kasemir** [comment]
For a test, I changed the `PKCS12_parse` call in `ossl.cpp` to use "changeit" as a password.
With that, `softIocPVX` can open the keytool-generated `ioc.p12`, and it will communicate with a java client that uses `trust_ca.p12`. The `pvxget` C++ client will read using `ioc.p12`, but with the more appropriate `trust_ca.p12` it complains `ssl/ssl_rsa.c:215:passed a null parameter, SSL_CCTX_use_certificate`.

**Comment by mdavidsaver** [comment]
> ... little sticky ...

> ... `ssl/ssl_rsa.c:215:passed a null parameter, SSL_CCTX_use_certificate` ...

These should be resolved.  fyi. the second actually caused `pvxsr 2` to SIGSEGV when a TLS client w/o certificate was connected.

**Comment by mdavidsaver** [comment]
```
$ keytool ... -storepass ""
keytool error: java.lang.Exception: Keystore password must be at least 6 characters
````

So keytool forces a password.  What is a non-interactive daemon supposed to do other than store that password right alongside the pkcs12 file?  Ah, the joys of CYA security!

I am tempted to invent some syntax like `EPICS_PVA_TLS_KEYCHAIN=/path/file.p12;password`.

**Comment by mdavidsaver** [comment]
A keytool generated file can be reprocessed with openssl w/o a password.  This losses the attributes which openssl doesn't understand.  friendlyName (aka `-alias`) and the `2.16.840.1.113894.746875.1.1` trust marker.

```
openssl pkcs12 -in some.p12 -out temp -passin pass:changeit -passout pass:
openssl pkcs12 -export -in temp -out another.p12  -passin pass: -passout pass:
```

**Comment by kasemir** [comment]
> some syntax like EPICS_PVA_TLS_KEYCHAIN=/path/file.p12;password

That's reasonable. We do need a password, even `""` is a password. We could store it in some "password manager", be it a custom file or the credential store that Windows and Mac OS offer, but that just shifts the issue one level up to providing the manager's password to then obtain the keychain password, and the IOC can't ask for the manager's password on startup.

**Comment by kasemir** [comment]
You indeed fixed the sticky tls behavior and the "null parameter, SSL_CCTX_use_certificate".

I can now read from softIocPVA with both pvxget and java client,
using either the openssl-generated ioc1.p12 (server) and ca.pem (client, imported into a trust_ca.p12),
or keytool-generated ioc.p12 and trust_ca.p12.
Also possible to intersperse plain TCP gets with the TLS gets.

**Comment by mdavidsaver** [comment]
Updated to add syntax for TLS in name servers.  `EPICS_PVA_NAME_SERVERS=pvas://1.2.3.4:5678`  Also for PKCS#12 files with password.  `EPICS_PVAS_TLS_KEYCHAIN=/path/to/some.p12;secret`.

**Comment by kasemir** [comment]
The new `EPICS_PVAS_TLS_KEYCHAIN=/path/to/some.p12;secret` works well for me, so does `EPICS_PVA_NAME_SERVERS=pvas://1.2.3.4:5076`.

A minor quirk is that `EPICS_PVA_NAME_SERVERS=pvas://1.2.3.4` with no port assumes port 5075, the default TCP port, while the TLS socket defaults to 5076, so must list the default TLS port as in `EPICS_PVA_NAME_SERVERS=pvas://1.2.3.4:5076`. But after users managed to create all those certificates, that's really minor.

**Comment by mdavidsaver** [comment]
Another update.

I am confident enough now in my understand of PKCS#12 file interoperability that I have removed `$EPICS_PVAS_CA_DIRS` and friends.  See `documentation/pkcs12.md` for my attempt to explain.  `test/gen_test_certs_j.sh` is derived form Kay's examples of keytool usage, and is intended to produce a set of .p12 files equivalent to `test/gen_test_certs.py`.  (not identical because keytool insists on a password...)

I have also added an "authority" member to `ClientCredentials`.  For methods "anonymous" and "ca" this is empty.  For "x509" this is the Common Name of the root CA.  Looking forward, for Kerberos this would be the realm name.

Certificate expiration date is now printed from `pvxsr` and various other places.  (not yet anything more)

I have also made failure to read/parse/setup TLS keychain a non-fatal error.  I could be persuaded to change this for the CLI tool, but I think it better that IOCs continue to start since this error can be corrected at runtime (with `pvxreconfigure`).

> ... with no port assumes port 5075, the default TCP port ...

Should be fixed.

**Comment by mdavidsaver** [comment]
I am also thinking about if/how to configure a "client cert. required" mode, which would make an public facing PVA gateway a less than totally insane proposition.

**Comment by kasemir** [comment]
>  "client cert. required" mode

Good question. On one hand, an option to require a client certificate sounds the proper thing to do.
On the other hand, I can easily run a client with "ioc.p12" and then it identifies as an IOC.
With "ca authentication" where it gets the user name from the OS I tend to get the actual name of who's running the client.

**Comment by mdavidsaver** [comment]
> ... an option ...

I also hesitate to have too many configuration options.  eg. I don't want to end up with dozens of `EPICS_PVA_TLS*` variable names (with matching `EPICS_PVAS_TLS*`).  So I don't want eg. `EPICS_PVA_TLS_CLIENT_CERT=REQUIRED`, but might go with something more open ended like `EPICS_PVA_TLS_OPTIONS=client_cert=required ...`.

**Comment by kasemir** [comment]
>> EPICS_PVA_NAME_SERVERS=pvas://1.2.3.4:5678 ... with no port assumes port 5075, the default TCP port ...

> Should be fixed.

It's now different. What I expected for EPICS_PVA_NAME_SERVERS:

 * `localhost` uses localhost port 5075 for a plain TCP search.
 * `localhost:5075` same with explicit port.

Those are still fine. But these..

 * `pvas://localhost` uses localhost port 5076 for a TLS search
 * `pvas://localhost:5076` same with explicit port

now result in 
`ERR pvxs.config EPICS_PVA_NAME_SERVERS ignoring invalid 'pvas://...' : URI unsupported in this context`

From the plain TCP 5075 search I will get a "tls" reply so the data is then via TLS, but I can no longer start with TLS for the search.

**Comment by kasemir** [comment]
Agree that how to handle authorization is beyond this.

Within this is supporting "ca" and "x509", and some way to select that on the client side (no certificate vs. client certificate with name) --> Done!

On the server side, not sure we need a "client cert required" option. That could be handled in the authorization, implemented later, based on the available information.
In a future authorization configuration file you can then control for example

"anonymous": No access
"ca": Read access
"x509": Read access plus for certain names write access

--> Server side is also done since we know if we get anon, ca or x509?

**Comment by mdavidsaver** [comment]
> On the server side, not sure we need a "client cert required" option. That could be handled in the authorization, implemented later, based on the available information.

My motivation to think about a special switch is twofold.  One technical, and one usability.

"client cert required" exists as a TLS protocol option (`SSL_VERIFY_FAIL_IF_NO_PEER_CERT`), which is set before any connection is opened, and is acted on before any application messages are exchanged.  Setting this flag would prevent anonymous clients from getting to a point of potentially sending malformed PVA messages.

Also, I think of this flag as analogous to the global read-only flags in the CA and PVA gateways.  Entirely redundant to a more fully featured ACL mechanism, but simpler to understand.  Hopefully also harder to misconfigure.

**Comment by kasemir** [comment]
You're correct that requiring the client cert offers a fail-early option. Yes, like the global read-only.

**Comment by mdavidsaver** [comment]
> URI unsupported in this context

This should be resolved.  Setting `pvxs::client::Config::nameServers` from code worked.  So `testtls` passed.  However, I had not changed the parsing when reading configuration from environment variables.  `testconfig` now covers `EPICS_PVA_NAME_SERVERS`.

At some point I should remove this duplicate parsing...

**Comment by kasemir** [comment]
..NAME_SERVERS now indeed handles "pvas://.." and that changes the default TCP port from 5075 to 5076, all good.

**Comment by mdavidsaver** [comment]
Development moved to main repository with https://github.com/mdavidsaver/pvxs/pull/53 .

**Pull request closed without merging**
